models/Account.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Account extends ActiveRecord 
{	
}

models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 */
class LoginForm extends Model
{
    public $email;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['email', 'password'], 'required'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect email or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return boolean whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findByEmail($this->email);
        }

        return $this->_user;
    }
}

models/User.php
<?php
namespace app\models;


use app\models\Account;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $createdAt;
    public $updatedAt;
    public $deleted;
    public $firstname;
    public $lastname;
    public $password;
    public $title;
    public $phone;
    public $mobile;
    public $fax;
    public $email;
    public $gender;
    public $role;
    public $companyId;
    public $authKey;
    public $accessToken;


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return Account::findOne($id) !== null ? new static(Account::findOne($id)) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (Account::find()->all() as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByEmail($email)
    {
        $user = Account::findOne(['email' => $email,]);

        if ($user !== null){
            return new static($user);
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/AccountController.php
<?php
namespace app\controllers;

use yii\web\Controller;
use app\models\Account;
use yii;

Yii::$app->view->params['start'] = 'none';

class AccountController extends Controller
{
    public function actionNew()
    {
        $query = Account::find();


        $accounts = $query->orderBy('firstname')->all();


       return $this->render('new', [
            'accounts' => $accounts,
        ]);
    }
}  

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Account;

Yii::$app->view->params['start'] = 'none';

class SiteController extends Controller
{

    public $start = "none";

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        //$this->start = "start";
        $this->view->params['start'] = 'start';
        $this->layout = "main";
        return $this->render('index');
    }

    public function actionContact()
    {
        return $this->render('contact');
    }

    public function actionConditions()
    {
        return $this->render('conditions');
    }

    public function actionImprint()
    {
        return $this->render('imprint');
    }

    public function actionPrice()
    {
        return $this->render('price');
    }

    public function actionPrivacypolicy()
    {
        return $this->render('privacypolicy');
    }

    public function actionRegistration()
    {
        return $this->render('registration');
    }

     public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $query = Account::find();
            $accounts = $query->orderBy('firstname')->all();
            return $this->render('../account/new', [
                'accounts' => $accounts,
            ]);
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\widgets\Menu;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="web/js/zoom.menu-min.js"></script>
    <link rel="stylesheet/less" type="text/css" href="../../web/css/main.less" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="content-wrapper">
    <div id="my-zoom-menu" class="zm-animation-wrapper zm-closed">
        <div class="zm-menu">
             <?php
                echo Menu::widget([
                    'options' => ['class' => 'zb-menu-list'],
                    'items' => [
                        ['label' => 'TransClac', 'url' => ['/site/index']],
                        ['label' => 'Preise', 'url' => ['/site/price']],
                        ['label' => 'Kontakt', 'url' => ['/site/contact']],
                        ['label' => 'Anmelden', 'url' => ['/site/registration']],
                        ['label' => 'AGBs', 'url' => ['/site/conditions']],
                        ['label' => 'Impressum', 'url' => ['/site/imprint']],
                        Yii::$app->user->isGuest ?
                            ['label' => 'Login', 'url' => ['/site/login']] :
                            [
                                'label' => 'Logout ',
                                'url' => ['/site/logout'],
                                'linkOptions' => ['data-method' => 'post']
                            ],
                                ],
                            ]);
            ?>
        </div>
        <div class="menu-button" id="menu-button" onclick="zoomMenu.show();">
            <div class="nv-line"></div>
            <div class="nv-line"></div>
            <div class="nv-line"></div>
        </div>
        <div class="zm-content-wrapper">
            <div class="zm-content" id="zm-content">
                <div class="head-line <?php if ($this->params['start'] !=='start') echo 'inAppHead' ?>" id="header" align="center">
                         <img src="web/images/transcalc-logo.png"  >
                         <h2 align="center">Mit geringnem Aufwand <br><b>Geld gespart!</b></br></h2>
                </div>
                <div class="menu <?php if ($this->params['start'] !=='start') echo 'inAppMenu' ?>" id="menu">
                    <div class="menu-logo"><img src="web/images/transcalc-logo.png"></div>
                    <?php
                        echo Menu::widget([
                            'options' => ['class' => 'menu-list'],
                            'items' => [
                                ['label' => 'TransClac', 'url' => ['/site/index']],
                                ['label' => 'Preise', 'url' => ['/site/price']],
                                ['label' => 'Kontakt', 'url' => ['/site/contact']],
                                ['label' => 'Anmelden', 'url' => ['/site/registration']],
                            ],
                        ]);
                    ?>
                    <div class="clear"></div>
                </div>
                <div id="site-content">
                    <?= $content ?>
                </div>
                <footer class="footer">
                    <?php
                        echo Menu::widget([
                            'options' => ['class' => 'zb-menu-list'],
                            'items' => [
                                ['label' => 'Anmeldung', 'url' => ['/site/registration']],
                                ['label' => 'Datenschutzerklärung', 'url' => ['/site/privacypolicy']],
                                ['label' => 'Impressum', 'url' => ['/site/imprint']],
                                ['label' => 'AGBs', 'url' => ['/site/conditions']],
                                ['label' => 'Kontakt', 'url' => ['/site/contact']],
                            ],
                        ]);
                    ?>
                    <img src="web/images/transcalc-logo-small.png">
                    <p class="copyright">&copy; <?= date('Y') ?> Copyright Transcalc GmbH </p>
                </footer>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var zoomMenu = new ZMZoomMenu('my-zoom-menu');
</script>
<script>
  less = {
    env: "development"
  };
</script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/conditions.php
<?php
/* @var $this yii\web\View */
$this->title = 'AGBs | TransClac';
?>

views/site/contact.php
<?php
/* @var $this yii\web\View */
$this->title = 'Kontakt | TransClac';
?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/imprint.php
<?php
/* @var $this yii\web\View */
$this->title = 'Impressum | TransClac';
?>

views/site/index.php
<?php
/* @var $this yii\web\View */
$this->title = 'Startseite | TransClac';
?>


<div id="scroll-to-about" class="about">
    <div class="about-what">
        <div class="about-img"><img src="web/images/transcalc-imac-what-it-is.jpg" ></div>
        <div class="about-text-wrapper">
            <div class="about-text">
                <h3>Konkurrenzfähig durch richtige Klalkulation</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec libero ex. Donec auctor lobortis orci in semper. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus ex risus, interdum ut feugiat non, sollicitudin ac dui. In purus ipsum, sollicitudin tincidunt ornare ac, fringilla vitae eros. Curabitur hendrerit aliquam ipsum nec pretium. Proin at tortor id lacus tincidunt eleifend.
                </p>  
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="about-sections">
        <h3>Konkurrenzfähig durch richtige Klalkulation</h3>
        <div class="about-section right text-middle-right">
            <div class="about-section-img"><img src="web/images/transcalc-packages.jpg" ></div>
            <div class="about-section-text">
              <div class="about-section-text-content">
                <p>
                   Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec libero ex. Donec auctor lobortis orci in semper. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus ex risus, interdum ut feugiat non, sollicitudin ac dui. In purus ipsum, sollicitudin tincidunt ornare ac, fringilla vitae eros. Curabitur hendrerit aliquam ipsum nec pretium. Proin at tortor id lacus tincidunt eleifend.
                </p>
              </div>
            </div>  
            <div class="clear"></div>         
        </div>
        <div class="about-section left img-middle-right">
            <div class="about-section-img"><img src="web/images/transcalc-transporter.jpg" ></div>
            <div class="about-section-text">
              <div class="about-section-text-content">
                <p >
                   In fringilla convallis diam non interdum. Vestibulum commodo libero non justo eleifend ornare. Vestibulum posuere erat congue justo suscipit pharetra sit amet a libero. Quisque sit amet tincidunt tellus. Ut quis nunc sed erat suscipit tristique eget eget enim. Sed tempus laoreet porta. Vestibulum vestibulum ligula in lectus condimentum, et scelerisque mauris elementum. Sed facilisis lorem ac nisi aliquam tempus a in leo. Aenean id libero gravida, convallis tortor placerat, blandit magna.
                </p>
              </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="about-section right img-middle-left">
            <div class="about-section-img"><img src="web/images/transcalc-calculator.jpg"></div>
            <div class="about-section-text">
              <div class="about-section-text-content">
                <p>
                    Sed convallis mauris massa, cursus laoreet ante elementum suscipit. Etiam eleifend risus elit, sed pretium nisi semper et. Pellentesque ipsum ante, mollis eu libero et, viverra interdum metus. Suspendisse ipsum neque, volutpat eget elementum non, rutrum sed sapien. Proin consequat metus eu neque tincidunt, nec egestas velit convallis. Praesent vestibulum dui a purus aliquet tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ullamcorper, ligula in porttitor aliquam, mi felis viverra leo, ut varius eros tellus eu orci. Praesent feugiat eu orci vel gravida. Fusce vel justo tincidunt, vestibulum nibh vitae, sagittis arcu. Morbi feugiat, erat nec consequat sodales, nunc felis venenatis nunc, id vestibulum ex mi vitae urna. Praesent vestibulum ipsum ut erat ultricies, in rhoncus felis volutpat. Fusce nibh ipsum, finibus in velit egestas, sodales sodales massa. Nunc sed magna quis tortor ullamcorper scelerisque. Donec finibus ex vitae urna convallis semper.
                </p>
              </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>


<div class="header-wrapper">
<div class="plan-header">
      <h2>Wähle deinen Plan!</h2>
      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.  </p>
    </div>
    <div class="plan-buttons">
      <div class="btn-group" id="button-wrapper">
        <a class="button selected" id="kostenlos" onclick="contentScroll(0)">Kostenlos</a><a class="button" id="proPlus" onclick="contentScroll(1)">Pro plus</a><a class="button" id="pro" onclick="contentScroll(2)">Pro</a>
      </div>
    </div>
    </div>
<div id="scroll-to-unsere-plane" class="unsere-plane">
    
    <div class="plan-super-wrapper" id="wrapper">
      <div class="plan-wrapper-kostenlos" id="kostenlosWrapper">
        <div class="upper-content">
          <div class="price">0,-</div>
          <div>
          <p>
            <h1 class="money">EUR</h1>
            <p>pro Monat</p>
            </p>
          </div>
        </div>
        <div class="middle-content">
          <ul>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
          </ul>
        </div>
        <div class="bottom-content">
          <button class="plan-content-button">jetzt Starten</button>
        </div>
      </div>
      <div class="plan-wrapper-pro-plus" id="proPlusWrapper">
        <div class="upper-content">
          <div class="price">99,-</div>
          <div>
            <h2 class="money">EUR</h2>
            <p>pro Monat</p>
          </div>
        </div>
        <div class="middle-content">
          <ul>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
          </ul>
        </div>
        <div class="bottom-content">
          <button class="plan-content-button">jetzt Starten</button>
        </div>
      </div>
      <div class="plan-wrapper-pro" id="proWrapper">
        <div class="upper-content">
          <div class="price">39,-</div>
          <div>
            <div class="money">EUR</div>
            <p>pro Monat</p>
          </div>
        </div>
        <div class="middle-content">
          <ul>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
            <li>Lorem ipsum dolor sit amet</li>
          </ul>
        </div>
        <div class="bottom-content">
          <button class="plan-content-button">jetzt Starten</button>
        </div>
      </div>
    </div>
    <div style="clear:both;"></div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h2>Betrete deinen Arbeitsplatz.</h2>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'login-form'],
        'fieldConfig' => [
            'template' => "{input}",
        ],
    ]); ?>

        <?= $form->field($model, 'email',['inputOptions' => ['placeholder' => 'Email',],]);?>

        <?= $form->field($model, 'password',['inputOptions' => ['placeholder' => 'Passwort',],])->passwordInput(); ?>
        <a class="password-forget" href="">Passwort vergessen?</a>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

        <a class="new-account" href="<?= Url::to(['site/registration']);?>">Du hast noch kein Konto?</a>

    <?php ActiveForm::end(); ?>
</div>

views/site/price.php
<?php
/* @var $this yii\web\View */
$this->title = 'Preise | TransClac';
?>

views/site/privacypolicy.php
<?php
/* @var $this yii\web\View */
$this->title = 'Datenschutzerklärung | TransClac';
?>

views/site/registration.php
<?php
/* @var $this yii\web\View */
$this->title = 'Anmeldung | TransClac';
?>